import { LegalPage } from '@/components/LegalPage';

export const metadata = { title: 'Terms of Service — HandleIt' };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="March 31, 2025">
      <section>
        <p>Welcome to HandleIt. By accessing or using our website and services at handleit.app (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). Please read them carefully before using the Service.</p>
        <p>These Terms constitute a legally binding agreement between you and HandleIt (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). If you do not agree to these Terms, do not use the Service.</p>
      </section>

      <section>
        <h2>1. Eligibility</h2>
        <p>You must be at least 18 years old to use HandleIt. By using the Service, you represent and warrant that you meet this age requirement and that you have the legal capacity to enter into this agreement.</p>
      </section>

      <section>
        <h2>2. Description of Service</h2>
        <p>HandleIt provides AI-powered tools to assist users with everyday administrative tasks, including form explanation, complaint letter drafting, and message reply generation. The Service is powered by large language model AI and is intended as an assistive tool only.</p>
        <p>HandleIt does not provide legal, financial, medical, or professional advice. All AI-generated content is for informational and drafting purposes only. You remain solely responsible for reviewing, editing, and using any output generated by the Service.</p>
      </section>

      <section>
        <h2>3. Account Registration</h2>
        <p>To access most features, you must create an account. You agree to:</p>
        <ul>
          <li>Provide accurate and complete registration information</li>
          <li>Maintain the security of your password and account credentials</li>
          <li>Notify us immediately of any unauthorized account access</li>
          <li>Take responsibility for all activity that occurs under your account</li>
        </ul>
        <p>We reserve the right to terminate accounts that violate these Terms.</p>
      </section>

      <section>
        <h2>4. Subscription Plans and Payment</h2>
        <p><strong>Free Plan:</strong> 5 total uses across all tools. No credit card required.</p>
        <p><strong>Pro Monthly:</strong> Unlimited uses billed at $17/month.</p>
        <p><strong>Pro Annual:</strong> Unlimited uses billed at $149/year.</p>
        <p><strong>Lifetime:</strong> One-time payment of $97 for unlimited lifetime access.</p>
        <p>All payments are processed securely via Paddle. By subscribing, you authorize us to charge your payment method on a recurring basis (for monthly/annual plans) until you cancel. Prices are in USD and subject to change with notice.</p>
      </section>

      <section>
        <h2>5. Cancellation</h2>
        <p>You may cancel your subscription at any time through your account Settings page. Cancellation takes effect at the end of the current billing period. You will retain access to Pro features until that date. We do not prorate refunds for unused time on monthly or annual subscriptions unless required by law. See our <a href="/legal/refund-policy">Refund &amp; Cancellation Policy</a> for full details.</p>
      </section>

      <section>
        <h2>6. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Generate content that is false, defamatory, harassing, or fraudulent</li>
          <li>Violate any applicable law or regulation</li>
          <li>Infringe the intellectual property rights of others</li>
          <li>Interfere with or disrupt the Service or its infrastructure</li>
          <li>Attempt to gain unauthorized access to any part of the Service</li>
          <li>Resell, sublicense, or commercially redistribute the Service without permission</li>
        </ul>
        <p>See our <a href="/legal/acceptable-use">Acceptable Use Policy</a> for full details.</p>
      </section>

      <section>
        <h2>7. Intellectual Property</h2>
        <p>The Service, including all software, design, branding, and content created by HandleIt, is owned by us and protected by intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the Service.</p>
        <p>You retain ownership of the content you input. You grant us a limited, non-exclusive license to process your inputs solely to deliver the Service to you. We do not use your personal inputs to train AI models.</p>
        <p>AI-generated outputs are provided to you for your personal or business use. You take full responsibility for reviewing and using any generated content.</p>
      </section>

      <section>
        <h2>8. Privacy</h2>
        <p>Your use of the Service is also governed by our <a href="/legal/privacy">Privacy Policy</a>, which is incorporated into these Terms by reference.</p>
      </section>

      <section>
        <h2>9. Disclaimer of Warranties</h2>
        <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL IMPLIED WARRANTIES INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI OUTPUTS WILL BE ACCURATE OR COMPLETE.</p>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, HANDLEIT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR $50, WHICHEVER IS GREATER.</p>
      </section>

      <section>
        <h2>11. Modifications to the Service and Terms</h2>
        <p>We reserve the right to modify, suspend, or discontinue any part of the Service at any time. We may update these Terms by posting revised Terms to this page. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
      </section>

      <section>
        <h2>12. Governing Law and Dispute Resolution</h2>
        <p>These Terms are governed by the laws of the United States. Any disputes shall first be attempted to be resolved informally by contacting us at legal@handleit.app. If informal resolution fails, disputes shall be resolved by binding arbitration in accordance with the rules of the American Arbitration Association. You waive your right to a jury trial and to participate in class action lawsuits.</p>
      </section>

      <section>
        <h2>13. Contact</h2>
        <p>For questions about these Terms, contact us at: <a href="mailto:legal@handleit.app">legal@handleit.app</a></p>
      </section>
    </LegalPage>
  );
}
