'use client';

import { useState } from 'react';

interface Props {
  result: string;
  color: string;
  toolId?: string; // 'letter' | 'form' | 'reply'
}

export function ResultDisplay({ result, color, toolId }: Props) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = () => {
    setDownloading(true);
    const win = window.open('', '_blank');
    if (!win) { setDownloading(false); return; }

    const htmlLines = result
      .split('\n')
      .map(line => {
        if (!line.trim()) return '<div style="height:10px"></div>';
        const clean = line.replace(/\*\*/g, '');
        if (line.startsWith('**') || (line.toUpperCase() === line && line.length < 50 && line.trim()))
          return `<p style="font-weight:700;margin:18px 0 6px;text-transform:uppercase;letter-spacing:0.06em;font-size:13px;color:#444;">${clean}</p>`;
        if (line.startsWith('• ') || line.startsWith('- '))
          return `<p style="margin:0 0 8px;padding-left:16px;">• ${line.slice(2)}</p>`;
        return `<p style="margin:0 0 10px;">${clean}</p>`;
      })
      .join('');

    win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>HandleIt — Complaint Letter</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      font-size: 15px;
      line-height: 1.85;
      color: #111;
      max-width: 680px;
      margin: 60px auto;
      padding: 0 40px 80px;
    }
    .header {
      border-bottom: 2px solid #111;
      padding-bottom: 14px;
      margin-bottom: 32px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }
    .header-brand { font-size: 13px; color: #888; font-family: Arial, sans-serif; }
    .header-title { font-size: 20px; font-weight: 700; letter-spacing: -0.02em; }
    .footer { margin-top: 60px; border-top: 1px solid #ddd; padding-top: 14px; font-size: 11px; color: #aaa; font-family: Arial, sans-serif; text-align: center; }
    @media print {
      body { margin: 40px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="header-title">Complaint Letter</div>
    <div class="header-brand">Generated by HandleIt · handleit.help</div>
  </div>
  <div class="content">${htmlLines}</div>
  <div class="footer">Generated by HandleIt &mdash; handleit.help</div>
  <script>
    window.onload = function() {
      setTimeout(function() { window.print(); }, 300);
    };
  </script>
</body>
</html>`);
    win.document.close();
    setTimeout(() => setDownloading(false), 1000);
  };

  const lines = result.split('\n').map((line, i) => {
    if (!line.trim()) return <div key={i} style={{ height: 8 }} />;
    const clean = line.replace(/\*\*/g, '');
    if (line.startsWith('**') || (line.toUpperCase() === line && line.length < 30 && line.trim()))
      return <div key={i} style={{ fontWeight: 700, color: 'white', marginTop: 16, marginBottom: 6, fontSize: 13, letterSpacing: '0.05em', textTransform: 'uppercase', opacity: 0.9 }}>{clean}</div>;
    if (line.startsWith('• ') || line.startsWith('- '))
      return <div key={i} style={{ display: 'flex', gap: 10, marginBottom: 6 }}><span style={{ color, marginTop: 3, flexShrink: 0 }}>•</span><span style={{ color: 'rgba(255,255,255,0.8)', fontSize: 14, lineHeight: 1.7 }}>{line.slice(2)}</span></div>;
    return <div key={i} style={{ color: 'rgba(255,255,255,0.75)', fontSize: 14, lineHeight: 1.7, marginBottom: 4 }}>{clean}</div>;
  });

  return (
    <div className="glass-card fade-up relative overflow-hidden" style={{ borderRadius: 24, padding: 24 }}>
      <div style={{ position: 'absolute', top: 0, left: '10%', right: '10%', height: '1px', background: 'linear-gradient(90deg,transparent,rgba(255,255,255,0.4),transparent)' }} />

      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16, flexWrap: 'wrap', gap: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 28, height: 28, borderRadius: '50%', background: color + '33', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, border: `1px solid ${color}50` }}>✓</div>
          <span style={{ color: 'white', fontWeight: 700, fontSize: 15 }}>Your Result</span>
        </div>

        <div style={{ display: 'flex', gap: 8 }}>
          {/* Copy button */}
          <button
            onClick={handleCopy}
            className="glass-btn"
            style={{ padding: '6px 14px', borderRadius: 14, fontSize: 12, fontWeight: 600, color: copied ? '#34D399' : 'rgba(255,255,255,0.7)', border: 'none', cursor: 'pointer', background: copied ? 'rgba(52,211,153,0.15)' : 'rgba(255,255,255,0.1)', transition: 'all 0.2s', fontFamily: 'inherit' }}
          >
            {copied ? '✓ Copied!' : '📋 Copy'}
          </button>

          {/* PDF Download — only on complaint letters */}
          {toolId === 'letter' && (
            <button
              onClick={handleDownloadPdf}
              className="glass-btn"
              style={{ padding: '6px 14px', borderRadius: 14, fontSize: 12, fontWeight: 600, color: downloading ? '#93C5FD' : 'rgba(255,255,255,0.7)', border: 'none', cursor: 'pointer', background: downloading ? 'rgba(26,86,219,0.2)' : 'rgba(255,255,255,0.1)', transition: 'all 0.2s', fontFamily: 'inherit' }}
            >
              {downloading ? '⏳ Opening…' : '⬇ Download PDF'}
            </button>
          )}
        </div>
      </div>

      <div style={{ borderTop: '1px solid rgba(255,255,255,0.08)', paddingTop: 16 }}>
        {lines}
      </div>
    </div>
  );
}
